---
id: 651a2cbc-a2ef-4af9-ad35-bdb3516e41cb
---
%%{init: {
  "theme": "forest",
  "themeVariables": {
    "gridColor": "transparent"
  },
  "gantt": {
    "todayMarker": false,
    "topPadding": 50,
    "leftPadding": 120,
    "fontSize": 12,
    "sectionFontSize": 14
  }
}}%%

gantt
  title Project Instance 1 Planting Schedule
  dateFormat  YYYY-MM
  axisFormat %b %Y

  section Baga FR
  Baga 1: active, a1, 2024-03, 91w
  Mponde: active, a2, 2024-03, 91w
  Kwesine: done, a3, 2024-05, 26w

  section Baga Ward
  Baga District     :active, a2, 2024-03, 91w
  Baga Ridge      : active,a1, 2024-03, 91w
  Baga-Mavului     :active, a2, 2024-03, 91w
  section Bombo Makole FR
  Site 1 :active, b1, 2025-03, 39w
  section Bwaya 
  Bwaya : active, d1, 2024-03, 91w
  section Magila-Kitamba 
  Magila-Kitamba :active, c1, 2025-03, 39w
  section Magamba FR
  Kwai             :active, c3, 2024-08, 64w
  Grewali         :done, c1, 2024-05, 56w
  Hambalawei      :done,c2, 2024-05, 56w
  Sungwi          :done, c3, 2024-05, 56w
  section Mgwashi 
  Mgwashi : active, e1, 2024-03, 91w
  section Mkussu FR
  Kifungiro : active, f1, 2024-03, 87w
  Kwesine :  done, f2, 2024-05, 26w
  Kwemashai: done, f2, 2024-05, 26w
  section Ndelemai FR
  West Site (1) : active, g1, 2024-03, 91w
  East Site (2) : active, g2, 2024-03, 91w

